# Set a rating
POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "player": "testPlayer",
  "game": "mastermind",
  "rating": 8,
  "ratedOn": "2023-10-01T12:00:00"
}

###

# Get average rating for a game
GET http://localhost:8080/api/rating/mastermind