# Add a score
POST http://localhost:8080/api/score
Content-Type: application/json

{
  "player": "testPlayer",
  "game": "mastermind",
  "points": 150,
  "playedOn": "2023-10-01T12:00:00"
}

###

# Get top scores for a game
GET http://localhost:8080/api/score/mastermind